language: node_js
node_js:
  - '0.12'
notifications:
  email: false
before_script:
  - git clone https://github.com/kasparsd/php-7-debian.git
  - cd php-7-debian
  - sudo ./build.sh > /dev/null
  - sudo ./install.sh > /dev/null
  - sudo ln -s /usr/local/php7/bin/php /usr/bin/php
  - php -v
script: npm run cover
after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
